User logon: GANYMEDE\jayes
Error occurred on: 15-Oct-2023 12:14:36
Culture/UI Culture: en-GB/en-GB
Current Thread - Culture/UI Culture: en-GB/en-GB
Calling assembly: Foundation.Tests.Unit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly location: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out\Foundation.Tests.Unit.dll
Executing assembly: Foundation.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly location: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out\Foundation.Common.dll
Environment.CurrentDirectory: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out
Directory.GetCurrentDirectory: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out

Error message: Message: A. 123
NestedExceptionFirstMethod
NestedExceptionSecondMethod
Ex3. P0:{0}. P1:{1}. P2:{2}.
Something has broken.
Error source: Foundation.Tests.Unit
Server name: GANYMEDE
Error Detail:
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Error message: NestedExceptionFirstMethod
Error source: Foundation.Tests.Unit
Exception type: System.Exception
Method source: Void NestedExceptionFirstMethod(Boolean)
Assembly name: Foundation.Tests.Unit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly location: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out\Foundation.Tests.Unit.dll
Assembly build: Debug MSIL
Assembly target framework: .NET Framework 4.8 - .NETFramework,Version=v4.8
Assembly Version: 1.0.0.0
Assembly File Version: 01.0.0.0
Assembly Configuration: Debug
Help link: 
Stack trace
   at Foundation.Tests.Unit.Foundation.Common.LoggingTests.Common.NestedExceptionFirstMethod(Boolean throwAsNew) in D:\Projects\JDVSoftware\Foundation.Net\Foundation.Tests.Unit\Foundation.Common\LoggingTests\Common.cs:line 29
   at Foundation.Tests.Unit.Foundation.Common.LoggingTests.FormattingTests.ExceptionOutputTests.TestNestedException_RethrowAsNewWithMessageFormat() in D:\Projects\JDVSoftware\Foundation.Net\Foundation.Tests.Unit\Foundation.Common\LoggingTests\FormattingTests\ExceptionOutputTests.cs:line 93

************************* Inner Exception Error Text **************************
Error message: NestedExceptionSecondMethod
Error source: Foundation.Tests.Unit
Exception type: System.Exception
Method source: Void NestedExceptionSecondMethod(Boolean)
Assembly name: Foundation.Tests.Unit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly location: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out\Foundation.Tests.Unit.dll
Assembly build: Debug MSIL
Assembly target framework: .NET Framework 4.8 - .NETFramework,Version=v4.8
Assembly Version: 1.0.0.0
Assembly File Version: 01.0.0.0
Assembly Configuration: Debug
Help link: 
Stack trace
   at Foundation.Tests.Unit.Foundation.Common.LoggingTests.Common.NestedExceptionSecondMethod(Boolean throwAsNew) in D:\Projects\JDVSoftware\Foundation.Net\Foundation.Tests.Unit\Foundation.Common\LoggingTests\Common.cs:line 48
   at Foundation.Tests.Unit.Foundation.Common.LoggingTests.Common.NestedExceptionFirstMethod(Boolean throwAsNew) in D:\Projects\JDVSoftware\Foundation.Net\Foundation.Tests.Unit\Foundation.Common\LoggingTests\Common.cs:line 20

************************* Inner Exception Error Text **************************
Error message: Ex3. P0:{0}. P1:{1}. P2:{2}.
Error source: Foundation.Tests.Unit
Exception type: System.Exception
Method source: Void NestedExceptionThirdMethod(Boolean)
Assembly name: Foundation.Tests.Unit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly location: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out\Foundation.Tests.Unit.dll
Assembly build: Debug MSIL
Assembly target framework: .NET Framework 4.8 - .NETFramework,Version=v4.8
Assembly Version: 1.0.0.0
Assembly File Version: 01.0.0.0
Assembly Configuration: Debug
Help link: 
Stack trace
   at Foundation.Tests.Unit.Foundation.Common.LoggingTests.Common.NestedExceptionThirdMethod(Boolean throwAsNew) in D:\Projects\JDVSoftware\Foundation.Net\Foundation.Tests.Unit\Foundation.Common\LoggingTests\Common.cs:line 67
   at Foundation.Tests.Unit.Foundation.Common.LoggingTests.Common.NestedExceptionSecondMethod(Boolean throwAsNew) in D:\Projects\JDVSoftware\Foundation.Net\Foundation.Tests.Unit\Foundation.Common\LoggingTests\Common.cs:line 39

************************* Inner Exception Error Text **************************
Error message: Something has broken.
Error source: Foundation.Tests.Unit
Exception type: System.Exception
Method source: Void NestedExceptionThirdMethod(Boolean)
Assembly name: Foundation.Tests.Unit, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Assembly location: D:\Projects\JDVSoftware\TestResults\Deploy_jayes 20231015T131433\Out\Foundation.Tests.Unit.dll
Assembly build: Debug MSIL
Assembly target framework: .NET Framework 4.8 - .NETFramework,Version=v4.8
Assembly Version: 1.0.0.0
Assembly File Version: 01.0.0.0
Assembly Configuration: Debug
Help link: 
Stack trace
   at Foundation.Tests.Unit.Foundation.Common.LoggingTests.Common.NestedExceptionThirdMethod(Boolean throwAsNew) in D:\Projects\JDVSoftware\Foundation.Net\Foundation.Tests.Unit\Foundation.Common\LoggingTests\Common.cs:line 58
